eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    
    
microservice:
  servicetype-service:
    endpoints:
      endpointbaseUri:
        uri: http://SERVICETYPE-SERVICE/
      endpoint1:
        uri: /service/allService
